spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/l2fi_test3?verifyServerCertificate=false&useSSL=false&requireSSL=false&autoReconnect=true&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull
    username: test
    password: test