spring:
  profiles:
    active: local #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 50MB #限制文件上传大小为10M

  jackson:
    time-zone: UTC

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 7889
  servlet:
    context-path: /fi
  address: 0.0.0.0
logging:
  file:
    path: logs
  level:
    com:
      wizz: debug
    org:
      springframework:
        web: debug

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.wizz.fi.dao.enums

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 123456 #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  signatureAlgorithm: HS256
