spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/l2fi?verifyServerCertificate=false&useSSL=false&requireSSL=false&autoReconnect=true&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull
    username: test
    password: test

ordinal:
  address: tb1pzxmvax02krvgw0tc06v7dz34zdvz9zynehcsfxky32h9zwg4nz4s9hk76h
  api: https://wallet-api-testnet.unisat.io/v5/address/inscriptions

token:
  rpc: http://127.0.0.1:8545
  contractAddress: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
  address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  privateKey: "privateKey"

wallet:
  mnemonic: "mnemonic"
  ordinal_path: "M/84H/1H/0H/1/0"
  change_path: "M/84H/1H/0H/0/0"
  change_address: "bcrt1qtkqmadt2j94aja0qx73ug75mu2zpa6tv473uu2"

mempool:
  host: https://mempool.space/testnet/api