spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/l2fi_test?verifyServerCertificate=false&useSSL=false&requireSSL=false&autoReconnect=true&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull
    username: test
    password: test

ordinal:
  api: https://wallet-api-testnet.unisat.io/v5/address/inscriptions

token:
  api: https://wallet-api-testnet.unisat.io/v5/address/inscriptions